project:
  owner: dsensiba@amazon.com
  name: test-project
  package_lambda: false
  regions:
    - us-east-1
    - us-east-2
    - us-west-1
    - us-west-2
  s3_bucket: ""
tests:
  test-scenario1:
    template: master.template
    regions:
      - us-east-1
